version: '3.7'

services:

  master:
    build: microservice/master-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  reservation:
    build: microservice/reservation-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  composite:
    build: microservice/composite-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  mysql:
    image: mysql
    mem_limit: 350m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=kmtp
      - MYSQL_USER=kyoung
      - MYSQL_PASSWORD=password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-uuser", "-ppwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
