server.port: 8880

spring.r2dbc:
  url: r2dbc:mysql://localhost:3306/kmtp?useUnicode=true&characterEncoding=utf8
  username: kyoung
  password: password

logging:
  level:
    root: INFO
    com.kmtp: DEBUG

app:
  master-service:
    host: localhost
    port: 8881
  reservation-service:
    host: localhost
    port: 8882

---
spring.profiles: docker

server.port: 8080

spring.r2dbc:
  url: r2dbc:mysql://mysql/kmtp?useUnicode=true&characterEncoding=utf8
  username: kyoung
  password: password

app:
  master-service:
    host: master
    port: 8080
  reservation-service:
    host: reservation
    port: 8080
