server:
  port: 8881

spring.jpa.hibernate.ddl-auto: create

spring.datasource.hikari:
  driver-class-name: org.h2.Driver
  jdbc-url: jdbc:h2:tcp://localhost:8889/mem:kmtp
  username: sa
  password: sa